// demos/solidstart/src/components/Grid.tsx
import { Index } from 'solid-js';
import {
  BaseGrid,
  GridHeader,
  GridHeaderCell,
  GridContent,
  GridContentRow,
  GridContentCell,
} from 'mitosis-components/solid';

export const Grid = (props: any) => {
  const colgroup = props.columns.map((i: any) => i.width);

  const gridHeader = (
    <GridHeader colgroup={colgroup} size="md">
      <Index each={props.columns}>
        {(col) => (
          <GridHeaderCell onClick={props.sort && props.sort(col)}>
            {col().title || col().field}
          </GridHeaderCell>
        )}
      </Index>
    </GridHeader>
  );

  const gridContent = (
    <GridContent colgroup={colgroup} size="md">
      <Index each={props.items}>
        {(item, i) => (
          <GridContentRow alt={i % 2 === 0}>
            <Index each={props.columns}>
              {(col) => (
                <GridContentCell>{item()[col().field]}</GridContentCell>
              )}
            </Index>
          </GridContentRow>
        )}
      </Index>
    </GridContent>
  );

  return (
    <BaseGrid
      slotGridHeader={gridHeader}
      slotGridContent={gridContent}
    ></BaseGrid>
  );
};

// demos/svelte/src/components/grid.svelte
<script>
    import BaseGrid from '../../../../packages/mitosis-components/output/svelte/src/grid/grid.svelte'
	import GridHeader from '../../../../packages/mitosis-components/output/svelte/src/grid/grid-header.svelte'
	import GridHeaderCell from '../../../../packages/mitosis-components/output/svelte/src/grid/grid-header-cell.svelte'
    import GridContent from '../../../../packages/mitosis-components/output/svelte/src/grid/grid-content.svelte'
    import GridContentRow from '../../../../packages/mitosis-components/output/svelte/src/grid/grid-content-row.svelte'
    import GridContentCell from '../../../../packages/mitosis-components/output/svelte/src/grid/grid-content-cell.svelte'


    export let items;
    export let columns;

    let colgroup = columns.map((i) => i.width);
</script>

<BaseGrid >
    <GridHeader slot="gridheader" colgroup={colgroup} size="md">
        {#each columns as col}
            <GridHeaderCell>
                { col.title || col.field }
            </GridHeaderCell>
        {/each }
    </GridHeader>
    <GridContent slot="gridcontent" colgroup={colgroup} size="md">
        {#each items as item, i}
            <GridContentRow alt={i % 2 === 0}>
                {#each columns as col}
                    <GridContentCell>
                        { item[col.field] }
                    </GridContentCell>
                {/each }
            </GridContentRow>
        {/each }
    </GridContent>
</BaseGrid>
