// packages/mitosis-components/output/svelte/src/grid/grid-content.svelte
<script>
  import Colgroup from "./colgroup.svelte";

  export let colgroup;
</script>

<div class="k-grid-content">
  <table class={tableClasses}>
    <Colgroup cols={colgroup} />
    <tbody class="k-table-tbody">
      <slot />
      <tr class="k-table-row">
        <td class="k-table-td">1</td>
        <td class="k-table-td">Row</td>
      </tr>
      <tr class="k-table-row k-table-alt-row k-alt">
        <td class="k-table-td">2</td>
        <td class="k-table-td">Alt row</td>
      </tr>
    </tbody>
  </table>
</div>

// packages/mitosis-components/output/qwik/src/grid/grid-content.jsx
import Colgroup from "./colgroup";

import { Fragment, Slot, component$, h } from "@builder.io/qwik";

export const GridContent = component$((props) => {
  return (
    <div class="k-grid-content">
      <table class={tableClasses}>
        <Colgroup cols={props.colgroup}></Colgroup>
        <tbody class="k-table-tbody">
          <Slot></Slot>
          <tr class="k-table-row">
            <td class="k-table-td">1</td>
            <td class="k-table-td">Row</td>
          </tr>
          <tr class="k-table-row k-table-alt-row k-alt">
            <td class="k-table-td">2</td>
            <td class="k-table-td">Alt row</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
});

export default GridContent;
