// packages/mitosis-components/output/react/src/grid/grid-content-row.jsx
import * as React from "react";
import { useState } from "react";

function GridContentRow(props) {
  const [rowClasses, setRowClasses] = useState(() =>
    props.alt ? `k-table-row k-table-alt-row k-alt` : `k-table-row`
  );

  return <tr className={rowClasses}>{props.children}</tr>;
}

export default GridContentRow;

// packages/mitosis-components/output/qwik/src/grid/grid-content-row.jsx
import { Fragment, Slot, component$, h, useStore } from "@builder.io/qwik";

export const GridContentRow = component$((props) => {
  const state = useStore({
    rowClasses: props.alt ? `k-table-row k-table-alt-row k-alt` : `k-table-row`,
  });

  return (
    <tr class={state.rowClasses}>
      <Slot></Slot>
    </tr>
  );
});

export default GridContentRow;
