// packages/mitosis-components/output/qwik/src/grid/grid.jsx
import { Fragment, component$, h } from "@builder.io/qwik";

export const Grid = component$((props) => {
  return (
    <div class="k-grid">
      {props.slotToolbar ? <>{props.slotToolbar}</> : null}
      {props.slotGridHeader}
      {props.slotGridContent}
      {props.slotPager ? <>{props.slotPager}</> : null}
    </div>
  );
});

export default Grid;

// packages/mitosis-components/output/react/src/grid/grid.jsx
import * as React from "react";

function Grid(props) {
  return (
    <div className="k-grid">
      {props.slotToolbar ? <>{props.slotToolbar}</> : null}

      {props.slotGridHeader}

      {props.slotGridContent}

      {props.slotPager ? <>{props.slotPager}</> : null}
    </div>
  );
}

export default Grid;
