// packages/mitosis-components/output/solid/src/grid/grid.jsx
import { Show } from "solid-js";

import Colgroup from "./colgroup.jsx";

function Grid(props) {
  return (
    <div class="k-grid">
      <Show when={props.slotToolbar}>
        <div class="k-grid-toolbae shtot sym mnogo qk">{props.slotToolbar}</div>
      </Show>
      <Colgroup cols={props.colgroup}></Colgroup>
      {props.children}
    </div>
  );
}

export default Grid;

// packages/mitosis-components/output/react/src/grid/grid.jsx
import * as React from "react";
import Colgroup from "./colgroup";

function Grid(props) {
  return (
    <div className="k-grid">
      {props.slotToolbar ? (
        <>
          <div className="k-grid-toolbae shtot sym mnogo qk">
            {props.slotToolbar}
          </div>
        </>
      ) : null}

      <Colgroup cols={props.colgroup} />

      {props.children}
    </div>
  );
}

export default Grid;
