// packages/mitosis-components/output/svelte/src/grid/grid-header.svelte
<script>
  import Colgroup from "./colgroup.svelte";

  export let colgroup;
</script>

<div class="k-grid-header">
  <div class="k-grid-header-wrap">
    <table class={tableClasses}>
      <Colgroup cols={colgroup} />
      <thead class="k-table-thead">
        <tr class="k-table-row">
          <slot />
        </tr>
      </thead>
    </table>
  </div>
</div>

// packages/mitosis-components/output/react/src/grid/grid-header.jsx
import * as React from "react";
import Colgroup from "./colgroup";

function GridHeader(props) {
  return (
    <div className="k-grid-header">
      <div className="k-grid-header-wrap">
        <table className={tableClasses}>
          <Colgroup cols={props.colgroup} />

          <thead className="k-table-thead">
            <tr className="k-table-row">{props.children}</tr>
          </thead>
        </table>
      </div>
    </div>
  );
}

export default GridHeader;
