// packages/mitosis-components/output/solid/src/grid/grid-content.jsx
import { createSignal } from "solid-js";

import Colgroup from "./colgroup.jsx";

function GridContent(props) {
  const [tableClasses, setTableClasses] = createSignal(
    `k-table k-table-${props.size} k-grid-header-table`
  );

  return (
    <div class="k-grid-content">
      <div class="k-grid-table-wrap">
        <table class={tableClasses()}>
          <Colgroup cols={props.colgroup}></Colgroup>
          <tbody class="k-table-tbody">{props.children}</tbody>
        </table>
      </div>
    </div>
  );
}

export default GridContent;

// packages/mitosis-components/output/react/src/grid/grid-content.jsx
import * as React from "react";
import { useState } from "react";
import Colgroup from "./colgroup";

function GridContent(props) {
  const [tableClasses, setTableClasses] = useState(
    () => `k-table k-table-${props.size} k-grid-header-table`
  );

  return (
    <div className="k-grid-content">
      <div className="k-grid-table-wrap">
        <table className={tableClasses}>
          <Colgroup cols={props.colgroup} />

          <tbody className="k-table-tbody">{props.children}</tbody>
        </table>
      </div>
    </div>
  );
}

export default GridContent;
