// packages/mitosis-components/output/qwik/src/grid/grid-header-cell.jsx
import { Fragment, Slot, component$, h } from "@builder.io/qwik";

export const GridHeaderCell = component$((props) => {
  return (
    <th class="k-table-th k-header">
      <span class="k-cell-inner">
        <span class="k-link">
          <span class="k-column-title">
            <Slot></Slot>
          </span>
        </span>
      </span>
    </th>
  );
});

export default GridHeaderCell;

// packages/mitosis-components/output/react/src/grid/grid-header-cell.jsx
import * as React from "react";

function GridHeaderCell(props) {
  return (
    <th className="k-table-th k-header">
      <span className="k-cell-inner">
        <span className="k-link">
          <span className="k-column-title">{props.children}</span>
        </span>
      </span>
    </th>
  );
}

export default GridHeaderCell;
